// Copyright 2026 luascfl. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"

	"github.com/mvanhorn/agentcookie/pkg/agentcookiesecret"
)

type Config struct {
	BaseURL               string            `toml:"base_url"`
	AuthHeaderVal         string            `toml:"auth_header"`
	Headers               map[string]string `toml:"headers,omitempty"`
	AuthSource            string            `toml:"-"`
	AccessToken           string            `toml:"access_token"`
	RefreshToken          string            `toml:"refresh_token"`
	TokenExpiry           time.Time         `toml:"token_expiry"`
	ClientID              string            `toml:"client_id"`
	ClientSecret          string            `toml:"client_secret"`
	Path                  string            `toml:"-"`
	LeadsBrasilBearerAuth string            `toml:"brasil_bearer_auth"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "http://localhost:8080/v1",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("LEADS_BRASIL_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "leads-brasil-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("LEADS_BRASIL_BEARER_AUTH"); v != "" {
		cfg.LeadsBrasilBearerAuth = v
		cfg.AuthSource = "env:LEADS_BRASIL_BEARER_AUTH"
	}

	// agentcookie secrets-bus overrides: per v0.13 wire-format section 11.2,
	// bus values win over both process env and config-file values. The reader
	// merges process env internally at lower priority, so this block only
	// applies values that actually came from the bus (plain or sealed). When
	// the bus is empty or unreachable, the existing env/config values stand.
	if busRes, busErr := agentcookiesecret.LoadDetailed("leads-brasil-pp-cli", ""); busErr != nil {
		if !errors.Is(busErr, agentcookiesecret.ErrInvalidCLIName) {
			log.Printf("agentcookiesecret: %v; continuing with config + env", busErr)
		}
	} else if busRes != nil {
		var busAuthSources []string
		if v, ok := busRes.Env["LEADS_BRASIL_BEARER_AUTH"]; ok && v != "" {
			if src := busRes.Sources["LEADS_BRASIL_BEARER_AUTH"]; src == agentcookiesecret.SourceBusPlain || src == agentcookiesecret.SourceBusSealed {
				cfg.LeadsBrasilBearerAuth = v
				busAuthSources = append(busAuthSources, "LEADS_BRASIL_BEARER_AUTH")
			}
		}
		if len(busAuthSources) > 0 {
			cfg.AuthSource = "bus:" + strings.Join(busAuthSources, ",")
		}
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.LeadsBrasilBearerAuth != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("LEADS_BRASIL_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.LeadsBrasilBearerAuth != "" {
		if c.AuthSource == "" {
			c.AuthSource = "env:LEADS_BRASIL_BEARER_AUTH"
		}
		return "Bearer " + c.LeadsBrasilBearerAuth
	}
	if c.AccessToken != "" {
		if c.AuthSource == "" || strings.HasPrefix(c.AuthSource, "env:") {
			c.AuthSource = "oauth2"
		}
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.LeadsBrasilBearerAuth = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
