// Copyright 2026 luascfl. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"

	"leads-brasil-pp-cli/internal/client"
	"leads-brasil-pp-cli/internal/cliutil"
	"leads-brasil-pp-cli/internal/config"

	"github.com/spf13/cobra"
)

// looksLikeDoctorInterstitial reports whether the response body matches a known
// bot-detection challenge page (Cloudflare, Akamai, Vercel, AWS WAF, DataDome,
// PerimeterX). Only fires on the doctor probe — used to distinguish "transport
// reached the wall" from "transport failed entirely." Returns the vendor name
// when matched, or empty string when no match.
//
// Markers are anchored to <title> or vendor-specific strings to avoid
// false-positives on benign content. For example, a recipe titled "Just A
// Moment of Pause Cookies" must NOT match the Cloudflare challenge marker;
// only "<title>just a moment" (the actual interstitial title) does.
func looksLikeDoctorInterstitial(body []byte) string {
	if len(body) == 0 {
		return ""
	}
	limit := len(body)
	if limit > 8192 {
		limit = 8192
	}
	prefix := strings.ToLower(string(body[:limit]))
	if !strings.Contains(prefix, "<title") {
		// Every bot interstitial we recognize sets a <title>; bodies without
		// one are body-only API responses, not challenge pages.
		return ""
	}
	switch {
	case strings.Contains(prefix, "<title>just a moment") || // CF JS challenge
		strings.Contains(prefix, "challenges.cloudflare.com") || // CF Turnstile
		(strings.Contains(prefix, "attention required") && strings.Contains(prefix, "cloudflare")):
		return "Cloudflare"
	case strings.Contains(prefix, "akamai") && (strings.Contains(prefix, "request unsuccessful") || strings.Contains(prefix, "access denied")):
		return "Akamai"
	case strings.Contains(prefix, "x-vercel-mitigated") || strings.Contains(prefix, "x-vercel-challenge-token") ||
		(strings.Contains(prefix, "vercel") && strings.Contains(prefix, "challenge")):
		return "Vercel"
	case strings.Contains(prefix, "request blocked") && strings.Contains(prefix, "aws waf"):
		return "AWS WAF"
	case strings.Contains(prefix, "datadome") && (strings.Contains(prefix, "blocked") || strings.Contains(prefix, "captcha") || strings.Contains(prefix, "challenge")):
		return "DataDome"
	case strings.Contains(prefix, "perimeterx") || strings.Contains(prefix, "px-captcha"):
		return "PerimeterX"
	}
	return ""
}

// suggestReadCommand walks the Cobra tree to find an endpoint-mirror command
// an operator can run to confirm credentials work end-to-end. Picks the
// first leaf that (a) carries the `pp:endpoint` annotation, so it actually
// dials the API rather than reading a local file like `feedback list` or
// `profile list`; (b) has a list/get verb; and (c) takes no positional
// arguments, so the suggestion is copy-paste runnable. Returns the dotted
// command path (e.g. "issues list") or "" when no such command exists —
// common in mutation-only CLIs and in CLIs where every read command has
// required positional arguments.
func suggestReadCommand(root *cobra.Command) string {
	if root == nil {
		return ""
	}
	var found string
	var walk func(*cobra.Command, []string)
	walk = func(cmd *cobra.Command, path []string) {
		if found != "" {
			return
		}
		for _, child := range cmd.Commands() {
			childPath := append(append([]string{}, path...), child.Name())
			if isSuggestableReadLeaf(child) {
				found = strings.Join(childPath, " ")
				return
			}
			// Recurse even into Hidden parents: printed CLIs mark raw
			// resource parents Hidden to keep --help curated, but their
			// endpoint leaves remain runnable (`<cli> projects list`
			// works). Skipping hidden subtrees would make this return ""
			// in nearly every CLI. isSuggestableReadLeaf still rejects a
			// leaf that is itself Hidden.
			walk(child, childPath)
			if found != "" {
				return
			}
		}
	}
	walk(root, nil)
	return found
}

func isSuggestableReadLeaf(cmd *cobra.Command) bool {
	if cmd == nil || cmd.Hidden || cmd.HasSubCommands() || !cmd.Runnable() {
		return false
	}
	// Only endpoint-mirror commands count; framework commands like
	// `feedback list` and `profile list` read local files and would
	// recreate the false-confidence failure mode the suggestion is
	// supposed to avoid.
	if cmd.Annotations["pp:endpoint"] == "" {
		return false
	}
	verb := strings.ToLower(strings.SplitN(cmd.Use, " ", 2)[0])
	if verb != "list" && verb != "get" {
		return false
	}
	// Endpoint commands with positional path params advertise them in
	// Use as `<id>` (required) or `[id]` (optional). The runtime body
	// rejects empty args by printing help, so suggesting one would not
	// actually exercise the token — reject before the Args probe below.
	if strings.ContainsAny(cmd.Use, "<[") {
		return false
	}
	// Probe the Args validator with an empty positional-arg list. A nil
	// validator accepts anything (including zero args); a non-nil validator
	// that returns nil for [] accepts zero args. Either qualifies — the
	// suggestion `<cli> list` is then a complete command.
	if cmd.Args == nil {
		return true
	}
	return cmd.Args(cmd, []string{}) == nil
}

func newDoctorCmd(flags *rootFlags) *cobra.Command {
	var failOn string
	var fix bool
	var forcePty bool
	cmd := &cobra.Command{
		Use:   "doctor",
		Short: "Check CLI health",
		Example: `  leads-brasil-pp-cli doctor
  leads-brasil-pp-cli doctor --json
  leads-brasil-pp-cli doctor --fail-on warn`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if os.Getenv("PP_LEADS_DOCTOR_PTY_ACTIVE") != "1" {
				wrapper := detectDefaultPtyWrapper()
				if wrapper == "" {
					// Sem wrapper detectado, segue no modo normal.
				} else {
				exe, err := os.Executable()
				if err != nil {
					return fmt.Errorf("doctor --pty: não consegui descobrir o executável atual: %w", err)
				}
				passthrough := []string{}
				for _, arg := range os.Args[1:] {
					if arg == "--pty" {
						continue
					}
					passthrough = append(passthrough, arg)
				}
				reexec := exec.Command("python3", append([]string{wrapper, "--", exe}, passthrough...)...)
				reexec.Stdin = os.Stdin
				reexec.Stdout = os.Stdout
				reexec.Stderr = os.Stderr
					reexec.Env = append(os.Environ(), "PP_LEADS_DOCTOR_PTY_ACTIVE=1")
					return reexec.Run()
				}
			}
			if fix {
				failOn = "stale"
			}
			if fix && !flags.noInput {
				fmt.Println("== Iniciando Setup Interativo (Goat/Leads) ==")
				reader := bufio.NewReader(os.Stdin)
				contactGoatStatus := map[string]any{}
				if out, err := exec.Command("contact-goat-pp-cli", "doctor", "--json").Output(); err == nil {
					_ = json.Unmarshal(out, &contactGoatStatus)
				}
				companyGoatStatus := map[string]any{}
				if out, err := exec.Command("company-goat-pp-cli", "doctor", "--json").Output(); err == nil {
					_ = json.Unmarshal(out, &companyGoatStatus)
				}
				hpAuth, _ := contactGoatStatus["auth"].(string)
				hpCookies, _ := contactGoatStatus["happenstance_cookies"].(string)
				hpAPI, _ := contactGoatStatus["happenstance_api_key"].(string)
				deeplineStatus, _ := contactGoatStatus["deepline_env"].(string)
				linkedinStatus, _ := contactGoatStatus["linkedin_profile"].(string)
				happenstanceReady := !strings.Contains(strings.ToLower(hpAuth), "not configured") || !strings.Contains(strings.ToLower(hpCookies), "not configured") || (hpAPI != "" && !strings.Contains(strings.ToLower(hpAPI), "not set"))
				deeplineReady := deeplineStatus != "" && !strings.Contains(strings.ToLower(deeplineStatus), "not set")
				linkedinReady := strings.HasPrefix(strings.ToLower(linkedinStatus), "ok")

				// CASA_DADOS_API_KEY
				if os.Getenv("CASA_DADOS_API_KEY") == "" && os.Getenv("PP_LEADS_CASA_DADOS_API_KEY") == "" {
					if doctorPromptYesNo(reader, "CASA_DADOS_API_KEY não está definida. Quer configurar agora para esta sessão? [s/N] ") {
						key := doctorPromptLine(reader, "Cole CASA_DADOS_API_KEY: ")
						if key != "" {
							os.Setenv("CASA_DADOS_API_KEY", key)
							fmt.Println("CASA_DADOS_API_KEY exportada para esta sessão.")
							fmt.Print("Persistir CASA_DADOS_API_KEY em ~/.config/leads-brasil-pp-cli/doctor.env? [s/N] ")
							persistAns, _ := reader.ReadString('\n')
							if strings.ToLower(strings.TrimSpace(persistAns)) == "s" || strings.ToLower(strings.TrimSpace(persistAns)) == "sim" {
								if err := persistDoctorEnvVar("CASA_DADOS_API_KEY", key); err != nil {
									fmt.Fprintf(os.Stderr, "falha ao persistir CASA_DADOS_API_KEY: %v\n", err)
								} else if envPath, err := doctorEnvPath(); err == nil {
									fmt.Printf("CASA_DADOS_API_KEY persistida em %s\n", envPath)
								}
							}
						}
					}
				}

				// Company Goat cache
				if cache, ok := companyGoatStatus["cache"].(map[string]any); ok {
					if status, _ := cache["status"].(string); status != "" && status != "ok" {
						if doctorPromptYesNo(reader, "Company Goat cache ainda não existe. Quer hidratar agora com company-goat-pp-cli sync --latest-only? [s/N] ") {
							syncCmd := exec.Command("company-goat-pp-cli", "sync", "--latest-only")
							syncCmd.Stdout = os.Stdout
							syncCmd.Stderr = os.Stderr
							syncCmd.Stdin = os.Stdin
							if err := syncCmd.Run(); err != nil {
								fmt.Fprintf(os.Stderr, "falha ao hidratar Company Goat: %v\n", err)
							}
						}
					}
				}

				// Happenstance
				if !happenstanceReady && runtime.GOOS == "darwin" {
					if doctorPromptYesNo(reader, "Rodar login do Happenstance pelo Chrome agora? [s/N] ") {
						c := exec.Command("contact-goat-pp-cli", "auth", "login", "--chrome", "--service", "happenstance")
						c.Stdout = os.Stdout
						c.Stderr = os.Stderr
						c.Stdin = os.Stdin
						if err := c.Run(); err != nil {
							fmt.Fprintf(os.Stderr, "falha ao executar comando: %v\n", err)
						}
					}
				} else if !happenstanceReady && os.Getenv("HAPPENSTANCE_API_KEY") == "" && os.Getenv("HAPPENSTANCE_WEB_APP_COOKIE_AUTH") == "" {
					fmt.Printf("Happenstance por cookies via Chrome não é suportado em %s.\n", runtime.GOOS)
					if doctorPromptYesNo(reader, "Quer configurar HAPPENSTANCE_API_KEY agora? [s/N] ") {
						key := doctorPromptLine(reader, "Cole HAPPENSTANCE_API_KEY: ")
						if key != "" {
							os.Setenv("HAPPENSTANCE_API_KEY", key)
							fmt.Println("HAPPENSTANCE_API_KEY exportada para esta sessão.")
							fmt.Print("Persistir HAPPENSTANCE_API_KEY em ~/.config/leads-brasil-pp-cli/doctor.env? [s/N] ")
							persistAns, _ := reader.ReadString('\n')
							if strings.ToLower(strings.TrimSpace(persistAns)) == "s" || strings.ToLower(strings.TrimSpace(persistAns)) == "sim" {
								if err := persistDoctorEnvVar("HAPPENSTANCE_API_KEY", key); err != nil {
									fmt.Fprintf(os.Stderr, "falha ao persistir HAPPENSTANCE_API_KEY: %v\n", err)
								} else if envPath, err := doctorEnvPath(); err == nil {
									fmt.Printf("HAPPENSTANCE_API_KEY persistida em %s\n", envPath)
								}
							}
						}
					}
					if doctorPromptYesNo(reader, "Se você já tiver um token web do contact-goat, quer configurá-lo agora via auth set-token? [s/N] ") {
						token := doctorPromptLine(reader, "Cole HAPPENSTANCE_WEB_APP_COOKIE_AUTH/token web: ")
						if token != "" {
							c := exec.Command("contact-goat-pp-cli", "auth", "set-token", token)
							c.Stdout = os.Stdout
							c.Stderr = os.Stderr
							c.Stdin = os.Stdin
							if err := c.Run(); err != nil {
								fmt.Fprintf(os.Stderr, "falha ao salvar token web do Happenstance: %v\n", err)
							}
						}
					}
				}

				// LinkedIn MCP
				if !linkedinReady && doctorPromptYesNo(reader, "Rodar setup do LinkedIn MCP agora? [s/N] ") {
					fmt.Fprintln(os.Stdout, "Tentando importar a sessão do navegador primeiro...")
					importCmd := exec.Command("uvx", "mcp-server-linkedin@latest", "--status", "--import-from-browser", "auto")
					importCmd.Stdout = os.Stdout
					importCmd.Stderr = os.Stderr
					importCmd.Stdin = os.Stdin
					if err := importCmd.Run(); err != nil {
						fmt.Fprintf(os.Stderr, "import automático do navegador falhou: %v\n", err)
						fmt.Fprintln(os.Stdout, "Caindo para login manual do LinkedIn MCP...")
						loginCmd := exec.Command("uvx", "mcp-server-linkedin@latest", "--login")
						loginCmd.Stdout = os.Stdout
						loginCmd.Stderr = os.Stderr
						loginCmd.Stdin = os.Stdin
						if err := loginCmd.Run(); err != nil {
							fmt.Fprintf(os.Stderr, "falha no login manual do LinkedIn MCP: %v\n", err)
						}
					}
					statusCmd := exec.Command("uvx", "mcp-server-linkedin@latest", "--status")
					statusCmd.Stdout = os.Stdout
					statusCmd.Stderr = os.Stderr
					statusCmd.Stdin = os.Stdin
					if err := statusCmd.Run(); err != nil {
						fmt.Fprintf(os.Stderr, "status final do LinkedIn MCP ainda falhou: %v\n", err)
					}
				}

				// DEEPLINE
				if !deeplineReady && os.Getenv("DEEPLINE_API_KEY") == "" {
					if doctorPromptYesNo(reader, "DEEPLINE_API_KEY não está definida. Quer configurar agora? [s/N] ") {
						key := doctorPromptLine(reader, "Cole DEEPLINE_API_KEY: ")
						if key != "" {
							os.Setenv("DEEPLINE_API_KEY", key)
							fmt.Println("DEEPLINE_API_KEY exportada para esta sessão.")
							fmt.Print("Persistir DEEPLINE_API_KEY em ~/.config/leads-brasil-pp-cli/doctor.env? [s/N] ")
							persistAns, _ := reader.ReadString('\n')
							if strings.ToLower(strings.TrimSpace(persistAns)) == "s" || strings.ToLower(strings.TrimSpace(persistAns)) == "sim" {
								if err := persistDoctorEnvVar("DEEPLINE_API_KEY", key); err != nil {
									fmt.Fprintf(os.Stderr, "falha ao persistir DEEPLINE_API_KEY: %v\n", err)
								} else if envPath, err := doctorEnvPath(); err == nil {
									fmt.Printf("DEEPLINE_API_KEY persistida em %s\n", envPath)
								}
							}
						}
					}
				}

								scrapeCreatorsHealthy := false
				if _, err := exec.LookPath("scrape-creators-pp-cli"); err == nil {
					checkCmd := exec.Command("scrape-creators-pp-cli", "account", "list", "--agent")
					if err := checkCmd.Run(); err == nil {
						scrapeCreatorsHealthy = true
					}
				}
				if !scrapeCreatorsHealthy {
					if doctorPromptYesNo(reader, "SCRAPE_CREATORS_API_KEY_AUTH está ausente ou inválida. Quer configurar agora? [s/N] ") {
						key := doctorPromptLine(reader, "Cole SCRAPE_CREATORS_API_KEY_AUTH: ")
						if key != "" {
							os.Setenv("SCRAPE_CREATORS_API_KEY_AUTH", key)
							fmt.Println("SCRAPE_CREATORS_API_KEY_AUTH exportada para esta sessão.")
							if doctorPromptYesNo(reader, "Persistir SCRAPE_CREATORS_API_KEY_AUTH em ~/.config/leads-brasil-pp-cli/doctor.env? [s/N] ") {
								if err := persistDoctorEnvVar("SCRAPE_CREATORS_API_KEY_AUTH", key); err != nil {
									fmt.Fprintf(os.Stderr, "falha ao persistir SCRAPE_CREATORS_API_KEY_AUTH: %v\n", err)
								} else if envPath, err := doctorEnvPath(); err == nil {
									fmt.Printf("SCRAPE_CREATORS_API_KEY_AUTH persistida em %s\n", envPath)
								}
							}
						}
					}
				}

fmt.Println("\nSe quiser persistir as chaves sem editar o shell manualmente, responda SIM aos prompts de persistência. Elas serão salvas em ~/.config/leads-brasil-pp-cli/doctor.env e carregadas automaticamente pela CLI.\nSe preferir, adicione ao seu ~/.bashrc ou ~/.zshrc:")
				fmt.Println("export CASA_DADOS_API_KEY=\"...\"")
				fmt.Println("export DEEPLINE_API_KEY=\"...\"")
				fmt.Println("\n== Doctor final ==")
			}

			report := map[string]any{}

			// --- EXTERNAL DEPENDENCIES (Goat/Leads) ---
			if os.Getenv("CASA_DADOS_API_KEY") == "" && os.Getenv("PP_LEADS_CASA_DADOS_API_KEY") == "" {
				report["Dependência Casa dos Dados"] = "error: ausente (requer CASA_DADOS_API_KEY)"
			} else {
				report["Dependência Casa dos Dados"] = "ok"
			}

			report["Dependência Deepline"] = "error: ausente (requer DEEPLINE_API_KEY ou discovery do contact-goat)"
			if cfgPath := os.Getenv("PP_LEADS_ICP_DIR"); cfgPath != "" {
				report["ICP Dir"] = "ok (env)"
			} else if cfgPath := detectDefaultUseCaseConfig(); cfgPath != "" {
				report["ICP Dir"] = "ok (auto-detect)"
			} else {
				report["ICP Dir"] = "warn: ausente (PP_LEADS_ICP_DIR não configurado e nenhum ICP padrão detectado)"
			}

			if _, err := exec.LookPath("company-goat-pp-cli"); err != nil {
				report["Dependência Company Goat"] = "error: ausente (company-goat-pp-cli não encontrado no PATH)"
			} else {
				report["Dependência Company Goat"] = "ok"
				if out, err := exec.Command("company-goat-pp-cli", "doctor", "--json").Output(); err == nil {
					var sub map[string]any
					if json.Unmarshal(out, &sub) == nil {
						if cache, ok := sub["cache"].(map[string]any); ok {
							if status, _ := cache["status"].(string); status != "" && status != "ok" {
								report["Company Goat Cache"] = "INFO cache status: " + status
							}
						}
					}
				}
			}

			if _, err := exec.LookPath("contact-goat-pp-cli"); err != nil {
				report["Dependência Contact Goat"] = "error: ausente (contact-goat-pp-cli não encontrado no PATH)"
			} else {
				report["Dependência Contact Goat"] = "ok"
				if out, err := exec.Command("contact-goat-pp-cli", "doctor", "--json").Output(); err == nil {
					var sub map[string]any
					if json.Unmarshal(out, &sub) == nil {
						if s, _ := sub["deepline_env"].(string); s != "" {
							if strings.Contains(strings.ToLower(s), "not set") {
								report["Dependência Deepline"] = "error: ausente (contact-goat sem Deepline)"
							} else {
								report["Dependência Deepline"] = "ok (" + s + ")"
							}
						}
						hpAuth, _ := sub["auth"].(string)
						cookies, _ := sub["happenstance_cookies"].(string)
						apiKeyStatus, _ := sub["happenstance_api_key"].(string)
						authMissing := hpAuth == "" || strings.Contains(strings.ToLower(hpAuth), "not configured")
						cookiesMissing := strings.Contains(strings.ToLower(cookies), "not configured")
						apiKeyMissing := apiKeyStatus == "" || strings.Contains(strings.ToLower(apiKeyStatus), "not set")
						switch {
						case authMissing && cookiesMissing && apiKeyMissing:
							if runtime.GOOS == "darwin" {
								report["Happenstance"] = "error: cookies e bearer ausentes"
								report["Happenstance Guidance"] = "INFO prefer login via Chrome cookies ou HAPPENSTANCE_API_KEY"
							} else {
								report["Happenstance"] = "error: cookies e bearer ausentes (import por Chrome indisponível em " + runtime.GOOS + ")"
								report["Happenstance Guidance"] = "INFO basta UMA surface válida: HAPPENSTANCE_API_KEY ou contact-goat-pp-cli auth set-token <token>"
							}
						case !authMissing && hpAuth != "":
							report["Happenstance"] = "ok (contact-goat auth configurado)"
						case !cookiesMissing && cookies != "":
							report["Happenstance"] = cookies
						case !apiKeyMissing:
							report["Happenstance"] = "ok (bearer API key configurada)"
						}
						if s, _ := sub["linkedin_profile"].(string); s != "" {
							if strings.Contains(strings.ToLower(s), "not logged in") {
								report["LinkedIn MCP"] = "error: login ausente"
							} else {
								report["LinkedIn MCP"] = s
							}
						}
					}
				}
			}

			if _, err := exec.LookPath("scrape-creators-pp-cli"); err != nil {
				report["Dependência Scrape Creators"] = "error: ausente (scrape-creators-pp-cli não encontrado no PATH)"
			} else {
				checkCmd := exec.Command("scrape-creators-pp-cli", "account", "list", "--agent")
				out, err := checkCmd.CombinedOutput()
				if err != nil {
					lower := strings.ToLower(string(out))
					switch {
					case strings.Contains(lower, "invalid api key"):
						report["Dependência Scrape Creators"] = "error: api key inválida"
					case strings.Contains(lower, "apikey is required") || strings.Contains(lower, "auth não configurada"):
						report["Dependência Scrape Creators"] = "error: auth não configurada"
					default:
						report["Dependência Scrape Creators"] = "error: falha ao validar auth"
					}
				} else {
					report["Dependência Scrape Creators"] = "ok"
				}
			}
			// --- END EXTERNAL DEPENDENCIES ---

			// Check config
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				report["config"] = fmt.Sprintf("error: %s", err)
			} else {
				report["config"] = "ok"
				report["config_path"] = cfg.Path
				report["base_url"] = cfg.BaseURL
			}

			// Check auth
			authConfigured := false
			if cfg != nil {
				header := cfg.AuthHeader()
				if header == "" {
					report["auth"] = "not configured"
					report["auth_hint"] = "export LEADS_BRASIL_BEARER_AUTH=<your-key>"
				} else {
					authConfigured = true
					report["auth"] = "configured"
					report["auth_source"] = cfg.AuthSource
				}
			}

			// Check auth environment variables
			authEnvSet := []string{}
			authEnvRequiredMissing := []string{}
			authEnvInfo := []string{}
			authEnvOptionalNames := []string{}
			// Validation rejects multi-OR-group specs upstream, so the single optional-satisfied state is sufficient at runtime.
			authEnvOptionalSatisfied := false
			if os.Getenv("LEADS_BRASIL_BEARER_AUTH") != "" {
				authEnvSet = append(authEnvSet, "LEADS_BRASIL_BEARER_AUTH")
			} else if authConfigured {
				authSource, _ := report["auth_source"].(string)
				if authSource == "" {
					authSource = "config"
				}
				authEnvInfo = append(authEnvInfo, "credentials available from "+authSource)
			} else {
				authEnvRequiredMissing = append(authEnvRequiredMissing, "LEADS_BRASIL_BEARER_AUTH")
			}
			switch {
			case len(authEnvRequiredMissing) > 0:
				report["env_vars"] = "ERROR missing required: " + strings.Join(authEnvRequiredMissing, ", ")
			case len(authEnvOptionalNames) > 1 && !authEnvOptionalSatisfied:
				report["env_vars"] = "INFO set one of: " + strings.Join(authEnvOptionalNames, " or ")
			case len(authEnvInfo) > 0 && authConfigured:
				report["env_vars"] = "OK " + strings.Join(authEnvInfo, "; ")
			case len(authEnvInfo) > 0:
				report["env_vars"] = "INFO " + strings.Join(authEnvInfo, "; ")
			default:
				report["env_vars"] = fmt.Sprintf("OK %d/%d available", len(authEnvSet), 1)
			}

			// Check API connectivity and validate credentials.
			//
			// The doctor uses the same client every other command uses --
			// flags.newClient() returns a *client.Client wrapping whatever
			// transport the spec declared (Surf for browser-chrome, stdlib
			// for standard). A separate stdlib http.Client would silently
			// bypass that choice and report false negatives against
			// Cloudflare-fronted, Akamai-fronted, or otherwise bot-detected
			// sites. By going through flags.newClient(), the doctor's
			// reachability verdict matches what real commands experience.
			if cfg != nil && cfg.BaseURL != "" {
				c, clientErr := flags.newClient()
				if clientErr != nil {
					report["api"] = fmt.Sprintf("client init error: %s", clientErr)
				} else {
					// Step 1: Basic reachability via the configured transport.
					reachBody, reachErr := c.Get(cmd.Context(), "/", nil)
					var reachAPIErr *client.APIError
					switch {
					case reachErr == nil:
						// 2xx response — clearly reachable. Still inspect the
						// body for a known interstitial; some bot walls return
						// 200 with a JS challenge page.
						if vendor := looksLikeDoctorInterstitial(reachBody); vendor != "" {
							report["api"] = fmt.Sprintf("blocked by %s interstitial — the configured transport reached the wall. Try a different network, wait for the IP-level rate limit to clear, or check that the browser-chrome transport is bound correctly.", vendor)
						} else {
							report["api"] = "reachable"
						}
					case errors.As(reachErr, &reachAPIErr):
						// Non-2xx from the server. The network reached, the
						// server responded — that's "reachable" for our
						// purposes. Inspect the response body for a known
						// interstitial first; otherwise note the status.
						status := reachAPIErr.StatusCode
						if vendor := looksLikeDoctorInterstitial([]byte(reachAPIErr.Body)); vendor != "" {
							report["api"] = fmt.Sprintf("blocked by %s interstitial (HTTP %d) — the configured transport reached the wall.", vendor, status)
						} else {
							report["api"] = fmt.Sprintf("reachable (HTTP %d at /)", status)
						}
					default:
						// Network-level failure: DNS, connection refused, TLS,
						// transport init, etc. The transport itself didn't
						// connect.
						report["api"] = fmt.Sprintf("unreachable: %s", reachErr)
					}

					// Step 2: Validate credentials with an authenticated probe.
					authHeader := cfg.AuthHeader()
					if authHeader == "" {
						// No auth configured — skip credential validation
					} else if reachErr != nil && !errors.As(reachErr, &reachAPIErr) {
						report["credentials"] = "skipped (API unreachable)"
					} else {
						suggestion := suggestReadCommand(cmd.Root())
						if suggestion != "" {
							report["credentials"] = fmt.Sprintf("present, not verified. Run `%s %s` to confirm the token works end-to-end.", "leads-brasil-pp-cli", suggestion)
						} else {
							report["credentials"] = "present, not verified. Run any read command to confirm the token works end-to-end."
						}
					}
				}
			} else if cfg != nil && cfg.BaseURL == "" {
				report["api"] = "not configured (set base_url in config file)"
			}

			// Verify mode state. Surfaced so an operator who unintentionally
			// inherits PRINTING_PRESS_VERIFY=1 (parent shell, CI runner, container
			// image) detects the foot-gun without inspecting a response body.
			// Pairs with the synthetic envelope's verify_noop / reason literals
			// as a second diagnosis anchor.
			if cliutil.IsVerifyEnv() {
				if cliutil.IsVerifyLiveHTTPEnv() {
					report["verify_mode"] = "INFO ACTIVE — live HTTP opt-in (mutating verbs dial out)"
				} else {
					report["verify_mode"] = "INFO ACTIVE — mutating HTTP verbs short-circuit (PRINTING_PRESS_VERIFY=1; no network calls for DELETE/POST/PUT/PATCH)"
				}
			} else {
				report["verify_mode"] = "normal operation"
			}

			report["version"] = version

			if flags.asJSON {
				if err := printJSONFiltered(cmd.OutOrStdout(), report, flags); err != nil {
					return err
				}
				return doctorExitForFailOn(failOn, report)
			}

			// Human-readable output with color
			w := cmd.OutOrStdout()
			checkKeys := []struct{ key, label string }{
				{"config", "Config"},
				{"auth", "Auth"},
				{"env_vars", "Env Vars"},
				{"verify_mode", "Verify Mode"},
				{"api", "API"},
				{"credentials", "Credentials"},
				{"Dependência Casa dos Dados", "Casa dos Dados (company)"},
				{"Dependência Deepline", "Deepline (contact)"},
				{"ICP Dir", "ICP Dir"},
				{"Dependência Company Goat", "Company Goat CLI"},
				{"Dependência Contact Goat", "Contact Goat CLI"},
				{"Dependência Scrape Creators", "Scrape Creators"},
				{"Happenstance", "Happenstance"},
				{"Happenstance Guidance", "Happenstance Guidance"},
				{"LinkedIn MCP", "LinkedIn MCP"},
				{"Company Goat Cache", "Company Goat Cache"},
			}
			for _, ck := range checkKeys {
				v, ok := report[ck.key]
				if !ok {
					continue
				}
				s := fmt.Sprintf("%v", v)
				indicator := green("OK")
				switch {
				case strings.HasPrefix(s, "INFO"):
					indicator = yellow("INFO")
				case strings.HasPrefix(strings.ToLower(s), "warn"):
					indicator = yellow("WARN")
				case strings.HasPrefix(s, "ERROR"):
					indicator = red("FAIL")
				case strings.HasPrefix(s, "optional"):
					// Optional-auth CLI with no key set — informational, not a failure.
					indicator = yellow("INFO")
				case strings.Contains(s, "scope-limited"):
					indicator = yellow("WARN")
				case strings.Contains(s, "not verified"):
					// "present, not verified" — credentials are loaded but no
					// probe ran. Informational, not a warning; a clean config
					// shouldn't render yellow WARN in CI dashboards.
					indicator = yellow("INFO")
				case strings.Contains(s, "error") || strings.Contains(s, "not configured") || strings.Contains(s, "unreachable") || strings.Contains(s, "invalid") || strings.Contains(s, "missing"):
					indicator = red("FAIL")
				case s == "not required":
					// Public APIs: no auth needed is a healthy state, not a warning.
					indicator = green("OK")
				case strings.Contains(s, "not ") || strings.Contains(s, "skipped") || strings.Contains(s, "inferred"):
					indicator = yellow("WARN")
				}
				fmt.Fprintf(w, "  %s %s: %s\n", indicator, ck.label, s)
			}
			// Print info keys without status indicator
			for _, key := range []string{"config_path", "base_url", "auth_source", "version"} {
				if v, ok := report[key]; ok {
					fmt.Fprintf(w, "  %s: %v\n", key, v)
				}
			}
			// Print auth setup hints (indented under Auth line)
			if hint, ok := report["auth_hint"]; ok {
				fmt.Fprintf(w, "  hint: %v\n", hint)
			}

			if !fix && !flags.noInput && doctorExitForFailOn("error", report) != nil {
				reader := bufio.NewReader(os.Stdin)
				if doctorPromptYesNo(reader, "\nRealizar o processo de fix agora? [s/N] ") {
					exe, err := os.Executable()
					if err != nil {
						return fmt.Errorf("doctor: não consegui reinvocar fix: %w", err)
					}
					fixCmd := exec.Command(exe, "doctor", "--fix")
					fixCmd.Stdin = os.Stdin
					fixCmd.Stdout = os.Stdout
					fixCmd.Stderr = os.Stderr
					fixCmd.Env = os.Environ()
					return fixCmd.Run()
				}
			}
			return doctorExitForFailOn(failOn, report)
		},
	}
	cmd.Flags().StringVar(&failOn, "fail-on", "", "Exit non-zero when a health level is reached: stale, error. Default is never.")
	cmd.Flags().BoolVar(&fix, "fix", false, "Run interactive setup to fix goat/auth dependencies")
	cmd.Flags().BoolVar(&forcePty, "pty", false, "Rerun doctor inside the standalone OMP-compatible PTY wrapper")
	_ = cmd.Flags().MarkHidden("fix")
	_ = cmd.Flags().MarkHidden("pty")
	return cmd
}


func doctorPromptYesNo(reader *bufio.Reader, prompt string) bool {
	for {
		fmt.Fprint(os.Stdout, prompt)
		answer, _ := reader.ReadString('\n')
		answer = strings.TrimSpace(strings.ToLower(answer))
		switch answer {
		case "", "n", "nao", "não", "no":
			return false
		case "s", "sim", "y", "yes":
			return true
		default:
			fmt.Fprintln(os.Stdout, "Entrada inválida. Responda s ou n.")
		}
	}
}

func doctorPromptLine(reader *bufio.Reader, prompt string) string {
	fmt.Fprint(os.Stdout, prompt)
	value, _ := reader.ReadString('\n')
	return strings.TrimSpace(value)
}

// doctorExitForFailOn returns a non-nil error when the report's worst
// status meets or exceeds the --fail-on threshold. "error" always trips
// when any section reports an error; "stale" also trips when the cache
// section is stale. The default empty string means never fail on status.
func doctorExitForFailOn(failOn string, report map[string]any) error {
	if failOn == "" {
		return nil
	}
	worstError := false
	worstStale := false
	for _, v := range report {
		s, ok := v.(string)
		if ok {
			lower := strings.ToLower(s)
			if strings.Contains(lower, "error") || strings.Contains(lower, "unreachable") || strings.Contains(lower, "invalid") || strings.Contains(lower, "missing") {
				worstError = true
			}
			if strings.HasPrefix(lower, "warn") {
				worstStale = true
			}
		}
		if m, ok := v.(map[string]any); ok {
			if st, _ := m["status"].(string); st == "error" {
				worstError = true
			} else if st == "stale" {
				worstStale = true
			}
		}
	}
	switch failOn {
	case "error":
		if worstError {
			return fmt.Errorf("doctor: --fail-on=error triggered")
		}
	case "stale":
		if worstError || worstStale {
			return fmt.Errorf("doctor: --fail-on=stale triggered")
		}
	default:
		return fmt.Errorf("doctor: unknown --fail-on value %q (valid: stale, error)", failOn)
	}
	return nil
}
