// Copyright 2026 luascfl. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLeadsBrasilPlatformSearchPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCnae string
	var bodyName string

	cmd := &cobra.Command{
		Use:         "leads-brasil-platform-search",
		Short:       "Search for companies by name or filter",
		Long:        "Search for companies by name or filter",
		Example:     "  leads-brasil-pp-cli leads-brasil-platform-search",
		Annotations: map[string]string{"pp:endpoint": "leads-brasil-platform-search.create", "pp:method": "POST", "pp:path": "/search"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/search"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyCnae != "" {
				body["cnae"] = bodyCnae
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCnae, "cnae", "", "Cnae")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
